apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: smart
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: smart-admin.lotusforthe.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-web
                port:
                  number: 3000
